title = "Mormann Lab for Cognitive and Clinical Neurophysiology"
baseURL = "https://mormannlab.github.io/"

theme = "ananke"
resourceDir = "../resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"

enableRobotsTXT = true


[services.googleAnalytics]
id = ''
[services.disqus]
shortname = 'YOURSHORTNAME'



[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = "Mormann's Lab"
# languageDirection = 'rtl' # for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"




[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe. Lets see what it means!"
background_color_class = "bg-black"
featured_image_class = "cover bg-top"
cover_dimming_class = "bg-blue-60"
recent_posts_number = 3
# For hovering shadow color (injected in the layouts/partials/site-style.html)
hover_shadow_color = "#007BFF" # Needs actual color code! #189AB4 #007BFF #05445E



# Social media links for sharing
[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "bluesky",
  "linkedin"
]

# Social media links for following
[params.ananke.social.follow]
networks = [
  "bluesky",
  "github"
]

[params.ananke.social.facebook]
username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

[params.ananke.social.bluesky]
username = "humansingleneuron.bsky.social"

[params.ananke.social.github]
username = "mormannlab"
